compatibilities = {
  "Virgo": {
    "Virgo": 10,
    "Cancer": 7,
    "Geminis": 2,
    "Piscis": 6,
    "Leo": 10,
    "Sagitario": 2,
    "Libra": 4,
    "Tauro": 7,
    "Aries": 8,
    "Escorpio": 2,
    "Capricornio": 2,
    "Acuario": 4
  },
  "Cancer": {
    "Virgo": 7,
    "Cancer": 9,
    "Geminis": 0,
    "Piscis": 0,
    "Leo": 5,
    "Sagitario": 7,
    "Libra": 7,
    "Tauro": 8,
    "Aries": 7,
    "Escorpio": 5,
    "Capricornio": 3,
    "Acuario": 6
  },
  "Geminis": {
    "Virgo": 6,
    "Cancer": 6,
    "Geminis": 7,
    "Piscis": 10,
    "Leo": 0,
    "Sagitario": 8,
    "Libra": 1,
    "Tauro": 3,
    "Aries": 0,
    "Escorpio": 7,
    "Capricornio": 0,
    "Acuario": 5
  },
  "Piscis": {
    "Virgo": 2,
    "Cancer": 3,
    "Geminis": 9,
    "Piscis": 8,
    "Leo": 4,
    "Sagitario": 6,
    "Libra": 8,
    "Tauro": 2,
    "Aries": 2,
    "Escorpio": 5,
    "Capricornio": 7,
    "Acuario": 0
  },
  "Leo": {
    "Virgo": 4,
    "Cancer": 4,
    "Geminis": 1,
    "Piscis": 7,
    "Leo": 5,
    "Sagitario": 4,
    "Libra": 3,
    "Tauro": 5,
    "Aries": 3,
    "Escorpio": 7,
    "Capricornio": 4,
    "Acuario": 7
  },
  "Sagitario": {
    "Virgo": 4,
    "Cancer": 4,
    "Geminis": 0,
    "Piscis": 8,
    "Leo": 6,
    "Sagitario": 1,
    "Libra": 6,
    "Tauro": 7,
    "Aries": 2,
    "Escorpio": 7,
    "Capricornio": 0,
    "Acuario": 10
  },
  "Libra": {
    "Virgo": 6,
    "Cancer": 2,
    "Geminis": 4,
    "Piscis": 5,
    "Leo": 5,
    "Sagitario": 8,
    "Libra": 6,
    "Tauro": 3,
    "Aries": 10,
    "Escorpio": 9,
    "Capricornio": 6,
    "Acuario": 2
  },
  "Tauro": {
    "Virgo": 5,
    "Cancer": 5,
    "Geminis": 10,
    "Piscis": 5,
    "Leo": 6,
    "Sagitario": 7,
    "Libra": 4,
    "Tauro": 3,
    "Aries": 7,
    "Escorpio": 7,
    "Capricornio": 6,
    "Acuario": 10
  },
  "Aries": {
    "Virgo": 7,
    "Cancer": 5,
    "Geminis": 2,
    "Piscis": 10,
    "Leo": 10,
    "Sagitario": 0,
    "Libra": 7,
    "Tauro": 9,
    "Aries": 5,
    "Escorpio": 3,
    "Capricornio": 7,
    "Acuario": 10
  },
  "Escorpio": {
    "Virgo": 5,
    "Cancer": 1,
    "Geminis": 7,
    "Piscis": 2,
    "Leo": 4,
    "Sagitario": 0,
    "Libra": 3,
    "Tauro": 2,
    "Aries": 6,
    "Escorpio": 5,
    "Capricornio": 3,
    "Acuario": 4
  },
  "Capricornio": {
    "Virgo": 5,
    "Cancer": 10,
    "Geminis": 3,
    "Piscis": 0,
    "Leo": 5,
    "Sagitario": 4,
    "Libra": 10,
    "Tauro": 10,
    "Aries": 7,
    "Escorpio": 9,
    "Capricornio": 1,
    "Acuario": 10
  },
  "Acuario": {
    "Virgo": 5,
    "Cancer": 0,
    "Geminis": 6,
    "Piscis": 8,
    "Leo": 10,
    "Sagitario": 4,
    "Libra": 7,
    "Tauro": 6,
    "Aries": 5,
    "Escorpio": 6,
    "Capricornio": 1,
    "Acuario": 4
  }
}

your_sign = raw_input('Dime tu signo zodiacal: ')
your_partners_sign = raw_input('Dime el signo zodiacal de tu pareja: ')

compatibility = compatibilities[your_sign][your_partners_sign]
print 'Su compatibilidad es de ' + str(compatibility) + '!'